name: denovonear

on: 
  push:
  schedule:
    - cron: "34 3 3 * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage coveralls
        pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: |
        python -m unittest discover
        denovonear cluster --in data/example_de_novos.txt --out output.txt
        denovonear cluster \
          --in data/example.grch38.dnms.txt  \
          --gencode data/example.grch38.gtf \
          --fasta data/example.grch38.fa \
          --out output.txt
        denovonear transcripts --de-novos data/example_de_novos.txt --out output.txt --all-transcripts
        denovonear rates --genes data/example_gene_ids.txt --out output.txt
        python -m coverage run --source=./denovonear -m unittest discover
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      run: |
        coveralls --service=github
